global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-server'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['api:9090']
        labels:
          service: 'api-server'

  - job_name: 'scheduler'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['scheduler:9090']
        labels:
          service: 'scheduler'

  - job_name: 'workers'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['worker:9090']
        labels:
          service: 'worker'

  # Add these if you're using node exporter for machine metrics
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100'] 