apiVersion: v1
kind: ConfigMap
metadata:
  name: task-scheduler-config
  namespace: task-scheduler
data:
  # Database configuration
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "taskdb"
  DB_SSLMODE: "disable"
  
  # Redis configuration
  REDIS_ADDR: "redis:6379"
  REDIS_DB: "0"
  
  # Logging configuration
  LOG_LEVEL: "info"
  
  # API configuration
  API_PORT: "8080"
  METRICS_PORT: "9090"
  
  # Worker configuration
  WORKER_COUNT: "5" 