apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: task-scheduler
type: Opaque
stringData:
  DB_USER: "taskuser"
  DB_PASSWORD: "password"  # Replace with a secure password in production

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: task-scheduler
type: Opaque
stringData:
  REDIS_PASSWORD: ""  # Replace with a password if Redis is configured with authentication 